apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apimocks.apirator.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Status
    type: string
  group: apirator.io
  names:
    kind: APIMock
    listKind: APIMockList
    plural: apimocks
    singular: apimock
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: APIMock is the Schema for the apimocks API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: APIMockSpec defines the desired state of APIMock
          properties:
            definition:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            serviceDefinition:
              properties:
                port:
                  type: integer
                serviceType:
                  description: Service Type string describes ingress methods for a
                    service
                  type: string
              type: object
            watch:
              type: boolean
          type: object
        status:
          description: APIMockStatus defines the observed state of APIMock
          properties:
            phase:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              enum:
              - PROVISIONED
              - ERROR
              - INVALID_OAS
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
